jumpbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  R_arm1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_arm1_joint
    pid: {p: 50.0, i: 0.01, d: 1.0, i_clamp_min: -10, i_clamp_max: 10}

  R_arm2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_arm2_joint
    pid: {p: 125.0, i: 0.01, d: 1.0, i_clamp_min: -10, i_clamp_max: 10}

  R_arm3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: R_arm3_joint
    pid: {p: 350.0, i: 0.01, d: 5.0, i_clamp_min: -10, i_clamp_max: 10}
  
  L_arm1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_arm1_joint
    pid: {p: 50.0, i: 0.01, d: 1.0, i_clamp_min: -10, i_clamp_max: 10}

  L_arm2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_arm2_joint
    pid: {p: 125.0, i: 0.01, d: 1.0, i_clamp_min: -10, i_clamp_max: 10}

  L_arm3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: L_arm3_joint
    pid: {p: 350.0, i: 0.01, d: 5.0, i_clamp_min: -10, i_clamp_max: 10}
